[Printer]
Language=English
Version=31
PrinterNum=4
DefaultPrinter=0
PrinterName0=RP-600
PrinterName1=PT-6300
PrinterName2=RP-700
PrinterName3=RP-630

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[RP-600]
SizeOfRam=81920000
MaxBmpOfRam=8

SizeOfFlash=389120000
MaxBmpOfFlash=255

SupportCut=1
SupportHerald=1
SupportWaterMark=1

MaxWidthOfBmp=510
MaxHeightOfBmp=768
MaxSizeOfBmp=98304

PageSupport=$FF
NetSupport=1
SupportPort=$3F

PaperNearEndSupport=1
Support2Color=1
SupportGray=1

RamFlashSupportBmp=$03
BmpSizeSupport=$0F

PrintType=0

AfterJKTime=2000
AfterEEPTime=8000
AfterCPTime=10000
OtherFileTime=5000

CodePageAreaNum=8
CodePageNumbegin=0
CodePageNumend=254

DefaultPort=0

ComName=0
BaudRate=7
Control=1
DataBits=0
StopBits=0
Parity=2

LPTAddr=0
USBID=0
EthernetIP=0.0.0.0
WIFIIP=0.0.0.0
DriverName=RP-600

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[PT-6300]
SizeOfRam=81920000
MaxBmpOfRam=8

SizeOfFlash=389120000
MaxBmpOfFlash=255

SupportCut=1
SupportHerald=1
SupportWaterMark=0

MaxWidthOfBmp=510
MaxHeightOfBmp=768
MaxSizeOfBmp=98304

PageSupport=$FF
NetSupport=0
SupportPort=$04

PaperNearEndSupport=0
Support2Color=0
SupportGray=0

RamFlashSupportBmp=$03
BmpSizeSupport=$0F

PrintType=0

AfterJKTime=2000
AfterEEPTime=8000
AfterCPTime=10000
OtherFileTime=5000

CodePageAreaNum=8
CodePageNumbegin=0
CodePageNumend=254

DefaultPort=0

ComName=0
BaudRate=7
Control=1
DataBits=0
StopBits=0
Parity=2

LPTAddr=0
USBID=0
EthernetIP=0.0.0.0
WIFIIP=0.0.0.0
DriverName=PT-6300

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[RP-700]
SizeOfRam=81920000
MaxBmpOfRam=8

SizeOfFlash=389120000
MaxBmpOfFlash=255

SupportCut=1
SupportHerald=1
SupportWaterMark=1

MaxWidthOfBmp=640
MaxHeightOfBmp=768
MaxSizeOfBmp=98304

PageSupport=$FF
NetSupport=1
SupportPort=$3F

PaperNearEndSupport=1
Support2Color=1
SupportGray=1

RamFlashSupportBmp=$03
BmpSizeSupport=$0F

PrintType=0

AfterJKTime=2000
AfterEEPTime=8000
AfterCPTime=10000
OtherFileTime=5000

CodePageAreaNum=8
CodePageNumbegin=0
CodePageNumend=254

DefaultPort=0

ComName=0
BaudRate=5
Control=1
DataBits=0
StopBits=0
Parity=2

LPTAddr=0
USBID=0
EthernetIP=0.0.0.0
WIFIIP=0.0.0.0
DriverName=RP-700

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[RP-630]
SizeOfRam=81920000 
MaxBmpOfRam=8 
SizeOfFlash=389120000
MaxBmpOfFlash=255

SupportCut=1 
SupportHerald=1
SupportWaterMark=1

MaxWidthOfBmp=640
MaxHeightOfBmp=768
MaxSizeOfBmp=98304

PageSupport=$FF
NetSupport=1
SupportPort=$2D

PaperNearEndSupport=0
Support2Color=1
SupportGray=1

RamFlashSupportBmp=$03
BmpSizeSupport=$0F

PrintType=0

AfterJKTime=2000
AfterEEPTime=8000
AfterCPTime=10000
OtherFileTime=5000

CodePageAreaNum=8
CodePageNumbegin=0
CodePageNumend=254

DefaultPort=0

ComName=0
BaudRate=5
Control=1
DataBits=0
StopBits=0
Parity=2

LPTAddr=0
USBID=0
EthernetIP=0.0.0.0
WIFIIP=0.0.0.0
DriverName=RP-630
